const chartTableInput = [
  {
    houseId: 1,
    houseSignName: "Sagittarius",
    houseSignLord: "Jupiter",
    houseNakshathraName: "Uttra Shadha",
    dhasaLord: "Sun",
    bukthiLord: "Rahu",
    antharaLord: "Rahu",
    sukLord: "Jupiter",
    degree: 269.2795392,
  },
  {
    degree: 273.754,
    planet: "Ketu",
    planetSignName: "Capricorn",
    planetSignLord: "Saturn",
    planetNakName: "Uttra Shadha",
    planetNakLord: "Sun",
    planetSubLord: "Saturn",
    planetSubSubLord: "Ketu",
    planetSubSubSubLord: "Mercury",
  },
  {
    houseId: 2,
    houseSignName: "Aquarius",
    houseSignLord: "Saturn",
    houseNakshathraName: "Dhanishtha",
    dhasaLord: "Mars",
    bukthiLord: "Mercury",
    antharaLord: "Saturn",
    sukLord: "Mercury",
    degree: 301.6746599,
  },
  {
    houseId: 3,
    houseSignName: "Pisces",
    houseSignLord: "Jupiter",
    houseNakshathraName: "Uttra Bhadrapad",
    dhasaLord: "Saturn",
    bukthiLord: "Mercury",
    antharaLord: "Ketu",
    sukLord: "Venus",
    degree: 335.7207759,
  },
  {
    degree: 7.9408,
    planet: "Moon",
    planetSignName: "Aries",
    planetSignLord: "Mars",
    planetNakName: "Ashwini",
    planetNakLord: "Ketu",
    planetSubLord: "Jupiter",
    planetSubSubLord: "Saturn",
    planetSubSubSubLord: "Sun",
  },
  {
    houseId: 4,
    houseSignName: "Aries",
    houseSignLord: "Mars",
    houseNakshathraName: "Ashwini",
    dhasaLord: "Ketu",
    bukthiLord: "Jupiter",
    antharaLord: "Saturn",
    sukLord: "Sun",
    degree: 7.9515588,
  },
  {
    houseId: 5,
    houseSignName: "Taurus",
    houseSignLord: "Venus",
    houseNakshathraName: "Krittika",
    dhasaLord: "Sun",
    bukthiLord: "Mercury",
    antharaLord: "Jupiter",
    sukLord: "Saturn",
    degree: 36.5124021,
  },
  {
    houseId: 6,
    houseSignName: "Gemini",
    houseSignLord: "Mercury",
    houseNakshathraName: "Mrigshira",
    dhasaLord: "Mars",
    bukthiLord: "Venus",
    antharaLord: "Venus",
    sukLord: "Venus",
    degree: 62.6902594,
  },
  {
    houseId: 7,
    houseSignName: "Gemini",
    houseSignLord: "Mercury",
    houseNakshathraName: "Punarvasu",
    dhasaLord: "Jupiter",
    bukthiLord: "Sun",
    antharaLord: "Mercury",
    sukLord: "Saturn",
    degree: 89.2795392,
  },
  {
    degree: 93.754,
    planet: "Rahu",
    planetSignName: "Cancer",
    planetSignLord: "Moon",
    planetNakName: "Pushya",
    planetNakLord: "Saturn",
    planetSubLord: "Saturn",
    planetSubSubLord: "Mercury",
    planetSubSubSubLord: "Venus",
  },
  {
    houseId: 8,
    houseSignName: "Leo",
    houseSignLord: "Sun",
    houseNakshathraName: "Magha",
    dhasaLord: "Ketu",
    bukthiLord: "Venus",
    antharaLord: "Rahu",
    sukLord: "Saturn",
    degree: 121.6746599,
  },
  {
    degree: 122.4054,
    planet: "Mars",
    planetSignName: "Leo",
    planetSignLord: "Sun",
    planetNakName: "Magha",
    planetNakLord: "Ketu",
    planetSubLord: "Venus",
    planetSubSubLord: "Saturn",
    planetSubSubSubLord: "Sun",
  },
  {
    houseId: 9,
    houseSignName: "Virgo",
    houseSignLord: "Mercury",
    houseNakshathraName: "Uttra Phalguni",
    dhasaLord: "Sun",
    bukthiLord: "Mercury",
    antharaLord: "Venus",
    sukLord: "Saturn",
    degree: 155.7207759,
  },
  {
    degree: 170.2313,
    planet: "Saturn",
    planetSignName: "Virgo",
    planetSignLord: "Mercury",
    planetNakName: "Hast",
    planetNakLord: "Moon",
    planetSubLord: "Ketu",
    planetSubSubLord: "Saturn",
    planetSubSubSubLord: "Mercury",
  },
  {
    degree: 177.1757,
    planet: "Jupiter",
    planetSignName: "Virgo",
    planetSignLord: "Mercury",
    planetNakName: "Chitra",
    planetNakLord: "Mars",
    planetSubLord: "Jupiter",
    planetSubSubLord: "Venus",
    planetSubSubSubLord: "Saturn",
  },
  {
    degree: 177.2535,
    planet: "Sun",
    planetSignName: "Virgo",
    planetSignLord: "Mercury",
    planetNakName: "Chitra",
    planetNakLord: "Mars",
    planetSubLord: "Jupiter",
    planetSubSubLord: "Venus",
    planetSubSubSubLord: "Mercury",
  },
  {
    degree: 186.1904,
    planet: "Mercury",
    planetSignName: "Libra",
    planetSignLord: "Venus",
    planetNakName: "Chitra",
    planetNakLord: "Mars",
    planetSubLord: "Moon",
    planetSubSubLord: "Saturn",
    planetSubSubSubLord: "Jupiter",
  },
  {
    houseId: 10,
    houseSignName: "Libra",
    houseSignLord: "Venus",
    houseNakshathraName: "Swati",
    dhasaLord: "Rahu",
    bukthiLord: "Rahu",
    antharaLord: "Venus",
    sukLord: "Venus",
    degree: 187.9515588,
  },
  {
    houseId: 11,
    houseSignName: "Scorpio",
    houseSignLord: "Mars",
    houseNakshathraName: "Anuradha",
    dhasaLord: "Saturn",
    bukthiLord: "Mercury",
    antharaLord: "Rahu",
    sukLord: "Rahu",
    degree: 216.5124021,
  },
  {
    degree: 222.3509,
    planet: "Venus",
    planetSignName: "Scorpio",
    planetSignLord: "Mars",
    planetNakName: "Anuradha",
    planetNakLord: "Saturn",
    planetSubLord: "Mars",
    planetSubSubLord: "Jupiter",
    planetSubSubSubLord: "Moon",
  },
  {
    houseId: 12,
    houseSignName: "Sagittarius",
    houseSignLord: "Jupiter",
    houseNakshathraName: "Mool",
    dhasaLord: "Ketu",
    bukthiLord: "Venus",
    antharaLord: "Mercury",
    sukLord: "Moon",
    degree: 242.6902594,
  },
];
export default chartTableInput;
